Rev #29 use travis

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,10 +40,10 @@ jobs:
         arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
         build-properties: '{ "All": "${{ matrix.log-options }} ${{  matrix.other-options }}" }'
 
-    - name: Setup Python
-      uses: actions/setup-python@master
-      with:
-        python-version: 3.7
+    #- name: Setup Python
+    #  uses: actions/setup-python@master
+    #  with:
+    #    python-version: 3.7
 
     #- name: Generate coverage report
     #  run: |
@@ -51,14 +51,22 @@ jobs:
     #    pip install pytest-cov
     #    pytest --cov=./ --cov-report=xml
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v1
-      with:        
-        file: ./coverage.xml
-        files: ./coverage1.xml,./coverage2.xml
-        directory: ./coverage/reports/
-        flags: unittests
-        env_vars: OS,PYTHON
-        name: codecov-umbrella
-        fail_ci_if_error: true
-        path_to_write_report: ./coverage/codecov_report.gz
+    #- name: Upload coverage to Codecov
+    #  uses: codecov/codecov-action@v1
+    #  with:        
+    #    file: ./coverage.xml
+    #    files: ./coverage1.xml,./coverage2.xml
+    #    directory: ./coverage/reports/
+    #    flags: unittests
+    #    env_vars: OS,PYTHON
+    #    name: codecov-umbrella
+    #    fail_ci_if_error: true
+    #    path_to_write_report: ./coverage/codecov_report.gz
+
+    - name: Use Travis build
+    run: |
+    ./build.sh
+
+    - name: Upload to codecov
+    run: |
+      bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports" -t ${{ Secrets.CODECOV_TOKEN }}
